# Generated by Django 5.1.4 on 2025-01-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("camp", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="parent_rec_area",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(name="RecAreaFacilityLink"),
    ]
