# Generated by Django 5.1.4 on 2025-01-01 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("camp", "0002_alter_facility_parent_rec_area_and_more")]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="facility_id",
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="facility",
            name="parent_rec_area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facilities",
                to="camp.recreationarea",
            ),
        ),
        migrations.AlterField(
            model_name="recreationarea",
            name="rec_area_id",
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="RecAreaFacilityLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="camp.facility"
                    ),
                ),
                (
                    "rec_area_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camp.recreationarea",
                    ),
                ),
            ],
        ),
    ]
