# Generated by Django 5.1.4 on 2025-01-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("camp", "0003_alter_facility_facility_id_and_more")]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="facility_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="recreationarea",
            name="rec_area_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
