# Generated by Django 5.1.4 on 2025-01-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("camp", "0005_alter_facility_facility_id_and_more")]

    operations = [
        migrations.RenameField(
            model_name="facility",
            old_name="parent_rec_area",
            new_name="parent_rec_area_id",
        )
    ]
