# Generated by Django 5.1.4 on 2025-01-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("camp", "0006_rename_parent_rec_area_facility_parent_rec_area_id")]

    operations = [
        migrations.RenameField(
            model_name="facility",
            old_name="parent_rec_area_id",
            new_name="parent_rec_area",
        )
    ]
