# Generated by Django 5.1.4 on 2025-01-01 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("camp", "0007_rename_parent_rec_area_id_facility_parent_rec_area")]

    operations = [
        migrations.CreateModel(
            name="Campsite",
            fields=[
                (
                    "campsite_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("campsite_type", models.CharField(max_length=100)),
                ("type_of_use", models.CharField(max_length=100)),
                ("loop", models.CharField(blank=True, max_length=100, null=True)),
                ("accessible", models.BooleanField(default=False)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("created_date", models.DateField()),
                ("last_updated_date", models.DateField()),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campsites",
                        to="camp.facility",
                    ),
                ),
            ],
        )
    ]
